version: '3.8'
services:
  postgres:
    image: mysql:5.7
    restart: always
    environment:
      - ./config/db.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
